cmake_minimum_required(VERSION 3.21)
project(HKTKOAuthMacOS VERSION 1.3.12 LANGUAGES C CXX)

if(NOT APPLE OR CMAKE_SYSTEM_NAME STREQUAL "iOS")
  message(FATAL_ERROR "HKTK OAuth macOS SDK only supports macOS")
endif()

add_library(HKTKSDKStatic STATIC IMPORTED GLOBAL)
set_target_properties(HKTKSDKStatic PROPERTIES
  IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/lib/libHKTKSDK.a"
  INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/include"
)
add_library(HKTKSDK::Static ALIAS HKTKSDKStatic)

add_library(HKTKSDKShared SHARED IMPORTED GLOBAL)
set_target_properties(HKTKSDKShared PROPERTIES
  IMPORTED_LOCATION "${CMAKE_CURRENT_LIST_DIR}/lib/libHKTKSDK.dylib"
  INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/include"
)
add_library(HKTKSDK::Shared ALIAS HKTKSDKShared)
